CREATE TABLE tb_AppRole
(

Id INTEGER,
Role_Name VARCHAR(100),
Is_Deleted BOOLEAN,
Created_On TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
Created_By VARCHAR(100),
Modified_On TIMESTAMP,
Modified_By VARCHAR(100),
Version INTEGER DEFAULT 1,
CONSTRAINT pk_tb_AppUser_Id PRIMARY KEY(Id)

);